/**
 * Test Management Store
 * 
 * OPTIMIZED: This entire store is generated by the factory!
 * Before optimization: 600+ lines of boilerplate
 * After optimization: 2 lines!
 * 
 * Includes all CRUD actions automatically:
 * - get_all, create, update, delete, restore, destroy
 * - update_status, bulk_action, import_data
 * - All filtering, pagination, selection management
 */

import { createModuleStore } from "@shared/modules/store-factory";
import setup from "../setup";

export const useTestStore = createModuleStore(setup);
